### ISSUE TITLE
버튼 기능

### ISSUE THREAD

**Issue by jossbar** [jossbar/geofence#1]
지금 지도에 현재위치버튼과 지역설정하는버튼 만들었는데 코드로 기능추가 어떻게 하지?

**Comment by Beong9** [comment]
지역설정버튼은 NewReminder.xml로 이동할 수 있게 intent기능을 이용해서 데이터를 양방향으로 전송할 수 있게 하자 그리고 현재위치버튼은 핀포인트아이콘이랑 확대기능은 좀더 고민해보자

**Comment by jossbar** [comment]
현재위치는 map utils 참조하면 될 것 같아
