### ISSUE TITLE
에러문구 

### ISSUE THREAD

**Issue by jossbar** [jossbar/geofence#3]
이거 컴파일 하다가 에러났는데 
Mainfest에서 무슨 에러가 있다는거 같은데 좀 찾아봐줘
Android resource linking failed
Output:  C:\Users\joss\Documents\geofence\app\build\intermediates\instant_run_merged_manifests\debug\processDebugManifest\instant-run\AndroidManifest.xml:49: error: resource string/title_activity_maps (aka com.example.app:string/title_activity_maps) not found.
error: failed processing manifest.

Command: C:\Users\joss\.gradle\caches\transforms-1\files-1.1\aapt2-3.2.1-4818971-windows.jar\e22e539aff66a7b4d03372ffcab0dbce\aapt2-3.2.1-4818971-windows\aapt2.exe link -I\
        C:\Users\joss\AppData\Local\Android\Sdk\platforms\android-28\android.jar\
        --manifest\
        C:\Users\joss\Documents\geofence\app\build\intermediates\instant_run_merged_manifests\debug\processDebugManifest\instant-run\AndroidManifest.xml\
        -o\

**Comment by Beong9** [comment]
Mainfest에서 문제가 아니고 resource Link에서 연결이 안되어있다는걸 보니 
아마 resource는 string에 있는 코드 인데 너가 stringfile에 코드를 잘못 건드린거 같다 
예전 masterbranch에 있는 코드를 보고 무슨 문제가 있는지 한번봐봐

**Comment by jossbar** [comment]
아 string에 title을 뺏었는데 넣으니까 바로 된다!
